#!/usr/bin/env python3
"""
merge_weights.py — Merge citation counts from citations.json into cartografia.json.

Usage:
    python scripts/merge_weights.py

Reads:
    citations.json              (generated by parse_ris.py)
    public/data/cartografia.json

Writes:
    public/data/cartografia.json  (updated in-place)

For each faro in cartografia.json, looks up its id in citations.json authors[*].faro_id.
If found: updates faro.citationCount with the citation_count value.
If not found: keeps existing value and prints a warning.

Updates generatedAt field to current ISO 8601 timestamp.
Validates the resulting JSON before writing.

Exit code 0 on success, 1 on validation failure.
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

# Import validate from validate_data.py (same scripts/ directory)
sys.path.insert(0, str(Path(__file__).parent))
from validate_data import validate


CITATIONS_PATH = Path("citations.json")
CARTOGRAFIA_PATH = Path("public/data/cartografia.json")


def load_json(path: Path) -> dict:
    """Load and parse a JSON file."""
    if not path.exists():
        print(f"Error: file not found: {path}", file=sys.stderr)
        sys.exit(1)
    try:
        with path.open(encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as exc:
        print(f"Error: invalid JSON in {path}: {exc}", file=sys.stderr)
        sys.exit(1)


def build_faro_id_to_citation(citations: dict) -> dict[str, int]:
    """
    Build a mapping from faro_id → citation_count from citations.json.

    citations.json structure:
        {
          "authors": {
            "Benjamin, Walter": {
              "faro_id": "benjamin",
              "citation_count": 23,
              ...
            }
          }
        }
    """
    mapping: dict[str, int] = {}
    authors = citations.get("authors", {})
    for author_name, author_data in authors.items():
        faro_id = author_data.get("faro_id")
        citation_count = author_data.get("citation_count", 0)
        if faro_id:
            # If multiple authors map to the same faro, sum their counts
            mapping[faro_id] = mapping.get(faro_id, 0) + citation_count
    return mapping


def main() -> int:
    # Load input files
    print(f"Reading: {CITATIONS_PATH}")
    citations = load_json(CITATIONS_PATH)

    print(f"Reading: {CARTOGRAFIA_PATH}")
    cartografia = load_json(CARTOGRAFIA_PATH)

    # Build faro_id → citation_count mapping
    faro_citation_map = build_faro_id_to_citation(citations)
    print(f"\nFaro citation mapping from citations.json:")
    for faro_id, count in sorted(faro_citation_map.items()):
        print(f"  {faro_id}: {count}")

    # Update citationCount for each faro
    faros = cartografia.get("faros", [])
    updated_count = 0
    not_found_count = 0

    print(f"\nUpdating faros:")
    for faro in faros:
        faro_id = faro.get("id", "<unknown>")
        if faro_id in faro_citation_map:
            old_count = faro.get("citationCount", 0)
            new_count = faro_citation_map[faro_id]
            faro["citationCount"] = new_count
            print(f"  ✓ {faro_id}: {old_count} → {new_count}")
            updated_count += 1
        else:
            existing = faro.get("citationCount", 0)
            print(f"  ⚠ {faro_id}: no citation data found, keeping existing value ({existing})",
                  file=sys.stderr)
            not_found_count += 1

    # Update generatedAt timestamp
    cartografia["generatedAt"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Validate the resulting JSON before writing
    print(f"\nValidating updated cartografia.json...")
    errors = validate(cartografia)
    if errors:
        print(f"\n✗ Validation failed with {len(errors)} error(s):\n", file=sys.stderr)
        for error in errors:
            print(f"  • {error}", file=sys.stderr)
        print(file=sys.stderr)
        return 1

    print("✓ Validation passed")

    # Write updated cartografia.json in-place
    CARTOGRAFIA_PATH.write_text(
        json.dumps(cartografia, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"\nUpdated: {CARTOGRAFIA_PATH}")

    # Summary
    print(f"\nSummary:")
    print(f"  Faros updated  : {updated_count}")
    print(f"  Faros not found: {not_found_count}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
